// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwapMeAngularAuthAPI.Context;

#nullable disable

namespace SwapMeAngularAuthAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230220192126_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("GenreId")
                        .IsUnique()
                        .HasFilter("[GenreId] IS NOT NULL");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Image", b =>
                {
                    b.Property<int>("GameImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameImageId"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageFile")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("GameImageId");

                    b.HasIndex("GameId")
                        .IsUnique()
                        .HasFilter("[GameId] IS NOT NULL");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPhysical")
                        .HasColumnType("bit");

                    b.Property<int>("OfferTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferId");

                    b.HasIndex("GameId");

                    b.HasIndex("OfferTypeId")
                        .IsUnique();

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.OfferType", b =>
                {
                    b.Property<int>("OfferTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferTypeId");

                    b.ToTable("OfferTypes");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("OfferId")
                        .IsUnique()
                        .HasFilter("[OfferId] IS NOT NULL");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserInfoId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserInfoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Game", b =>
                {
                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.Genre", "Genre")
                        .WithOne("Game")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.Game", "GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Image", b =>
                {
                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.Game", "Game")
                        .WithOne("Image")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.Image", "GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Offer", b =>
                {
                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.Game", "Game")
                        .WithMany("Offers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.OfferType", "OfferType")
                        .WithOne("Offer")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.Offer", "OfferTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.Platform", "Platform")
                        .WithOne("Offer")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.Offer", "PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.User", "Seller")
                        .WithMany("Offers")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("OfferType");

                    b.Navigation("Platform");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Transaction", b =>
                {
                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.User", "Buyer")
                        .WithMany("Transactions")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.Offer", "Offer")
                        .WithOne("Transaction")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.Transaction", "OfferId");

                    b.Navigation("Buyer");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.UserInfo", b =>
                {
                    b.HasOne("SwapMeAngularAuthAPI.Models.Entities.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("SwapMeAngularAuthAPI.Models.Entities.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Game", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Genre", b =>
                {
                    b.Navigation("Game");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Offer", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.OfferType", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.Platform", b =>
                {
                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SwapMeAngularAuthAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Transactions");

                    b.Navigation("UserInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
